services:
  db:
    image: postgres:16
    restart: unless-stopped
    ports:
      - "15432:5432"
    env_file:
      - .env.local
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data_local:/var/lib/postgresql/data

volumes:
  postgres_data_local:
