"""initial migration

Revision ID: f7f903c3f547
Revises: 
Create Date: 2025-11-09 15:09:29.966733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7f903c3f547'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_start', sa.DateTime(), nullable=True),
    sa.Column('game_end', sa.DateTime(), nullable=False),
    sa.Column('game_is_active', sa.Boolean(), nullable=True),
    sa.Column('setting_limitParameter', sa.Enum('DAY', 'WEEK', 'MONTH', 'GAME', name='limitparameter'), nullable=False),
    sa.Column('setting_limitValue', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_id'), 'games', ['id'], unique=False)
    op.add_column('like_transactions', sa.Column('game_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'like_transactions', 'games', ['game_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'like_transactions', type_='foreignkey')
    op.drop_column('like_transactions', 'game_id')
    op.drop_index(op.f('ix_games_id'), table_name='games')
    op.drop_table('games')
    # ### end Alembic commands ###
